# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - sldemoapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://swaticr.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_7b49f95cd9b745d69091930f78a76e79 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_a3c0d2923bb24df49ee6e527f5b4443f }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: swaticr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_7b49f95cd9b745d69091930f78a76e79 }}/azurecontainerappdemo:${{ github.sha }}
        file: ./AzureContainerAppDemo/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'sldemoapp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_4e7a0395e4d949658c05f75ef1058441 }}
        images: 'swaticr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_7b49f95cd9b745d69091930f78a76e79 }}/azurecontainerappdemo:${{ github.sha }}'